spring.application.name=attendance
#spring.datasource.url=jdbc:postgresql://localhost:5432/efco_attendance
#spring.datasource.username=postgres
#spring.datasource.password=Munch@08
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://attendance-db.clucs0wsw8vz.ap-south-1.rds.amazonaws.com:5432/attendance_db
spring.datasource.username=postgres
spring.datasource.password=EfcoHyd2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=MunchSecretKeyForJWTAttendanceApp
jwt.expiration=86400000

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=adminteklance@gmail.com
spring.mail.password=imonrsrormjvtxoe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.properties.mail.smtp.starttls.enable=true
